version: "3.6"

services: 
  web:
    build: 
      context: ./
      dockerfile: docker/nginx/Dockerfile
    ports: 
      - "8383:80" 
    volumes: 
      - ./code:/code
      - ./docker/nginx/config/site.conf:/etc/nginx/conf.d/site.conf
    links: 
      - php
  
  php:
    build: 
      context: ./
      dockerfile: docker/php/Dockerfile
    volumes: 
      - ./code:/code
    