version: "3.6"

services: 
  web:
    build: 
      context: ./
      dockerfile: docker/nginx/Dockerfile
    ports: 
      - "8383:80" 
    volumes: 
      - ./code:/code:cached
      - ./docker/nginx/config/default.conf:/etc/nginx/conf.d/default.conf
    links: 
      - php
  
  php:
    build: 
      context: ./
      dockerfile: docker/php/Dockerfile
    working_dir: /code
    volumes: 
      - ./code:/code
    ports: 
      - "9000:80"
    