version: "3.6"

services: 

  app:
    build: 
      context: ..
      dockerfile: docker/app/Dockerfile
    working_dir: /var/www
    volumes: 
      - ../src:/var/www:cached
    ports: 
      - "9000:80"
    depends_on: 
      - database

  web:
    build: 
      context: ..
      dockerfile: docker/nginx/Dockerfile
    depends_on:
      - app
    volumes: 
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports: 
      - "8080:80"

  database:
    restart: always
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    volumes: 
      - ../data:/var/lib/mysql
    ports: 
      - '3333:3306'
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DB_USER: root

  phpmyadmin:
    restart: always
    image: molengeekdev/phpmyadmin
    ports:
      - '8181:80'
    environment: 
      - PMA_HOSTS=database